version: '3'
services:
  devlopment:
    build: .
    tty: true
    volumes:
      - ./:/app
      - node_modules_volume:/app/node_modules
    working_dir: /app
    ports:
      - 5050:5050
volumes:
  node_modules_volume:
